### ISSUE TITLE
API Docs or examples?

### ISSUE THREAD

**Issue by edi** [iddan/react-spreadsheet#49]
Hello! I seem to have a hard time finding any of that **Simple straightforward API** documentation?

Some of the questions would be: 
1. How do I define cell formulas on mount? If I pass them in the **data** prop, it'd just return **#VALUE!**.

2. How do I detect cell value changes ?
3. How do I programmatically update a cell ( if possible ) ?

I mean, is there any full use-case example I could happily look into?
The project looks very nice compared to everything else, but I have a hard time figuring out how to use actually use any of it ..

Please advise, thanks!

**Comment by iddan** [comment]
Hey, thank you for giving React Spreadsheet a try. Yes, I agree the project lacks some documentation but I'd be very happy to get some with that! As for your questions:
1. Currently, we don't support custom formula functions but this is a feature that is very easy to implement. 
2. To detect cell value changes you can either pass the `<Spreadsheet />` component `onChange` function prop which will be called every time a cell value is changed (i.e. every character added to a cell)  or `onCellCommit` function prop which will be called every time a cell editing is done (i.e. after closing an edited cell).
3. You can update a cell programmatically by changing the provided data prop value just like any other prop in React.
If you have further questions or something I wrote is not clear please feel free to comment.

**Comment by EduardJS** [comment]
Hey @iddan! Thank for the answer and sorry for my late reply.

Points **2** and **3** are pretty self explanatory, thanks for that.
Regarding point **1** though, I'm not interested in custom functions. I can do with the currently existing ones from the parser, what I'm interested in is how to get the component to calculate the actual formulas on mount, when the given data looks like this for example:

```
const data = [
  [{ value: "Eivind" }, { value: 55 }],
  [{ value: "Sven" }, { value: 32 }],
  [{ value: "Total" }, { value: '=B1+B2' }],
  [{ value: "Percentage" }, { value: '=B1/B2*100' }]
];
```

It looks like the following:
![image](https://user-images.githubusercontent.com/7712869/66333094-df977500-e93e-11e9-8c3b-5f7f8ce5cd95.png)

But, if I simply click on the cells, the values are calculated correctly.
![image](https://user-images.githubusercontent.com/7712869/66333156-fb028000-e93e-11e9-9f8e-4d61c086d4d6.png)

Any clue about that? In my opinion it should detect the formulas on mount, otherwise functions are kind of pointless, as they'd only work on user input (after the component mounted).

Or is that the wanted behavior?
Regards!

**Comment by iddan** [comment]
Hey, thanks for clarifying. It seems like a bug. I'm currently a little busy so can you take a look and if you don't find a quick fix I'll fix it myself?

**Comment by EduardJS** [comment]
Sure can. I will look into it, though I’m not that familiar with TS.

**Comment by iddan** [comment]
The codebase is in JavaScript with Flow, not TypeScript. You can ignore types if you aren't familiar with them.

**Comment by aitorCerecetoGlovoApp** [comment]
Hello, any plans to get some proper docs?

**Comment by iddan** [comment]
Hey @aitorCerecetoGlovoApp, thank you for asking. At the moment I can not find the time to write proper documentation but in the midtime: is there a specific question I can answer?

**Comment by aitorCerecetoGlovoApp** [comment]
hello @iddan , how can I refresh the table? I have the matrix changd in the backend but for some reason the table is not refreshed with new data even using a setSpreadsheet hook.

**Comment by iddan** [comment]
Sorry for the super late response, can you provide your code?

**Comment by iddan** [comment]
Added props documentation to website https://iddan.github.io/react-spreadsheet/docs/usage.
